// ---------------------------------------------------------------------------
// DATA: All 331 US government GitHub organisations
// Source: github/government.github.com/_data/governments.yml (U.S. sections only)
// Grouped into 8 categories matching the YAML structure.
// Each entry has:
//   name     - the GitHub organisation slug (used in API calls)
//   category - the section from governments.yml
//   emoji    - visual indicator for the category in the UI
// ---------------------------------------------------------------------------

export const ORGS = [
  // ── U.S. Federal (164 orgs) ───────────────────────────────────────────────
  { name: "18f", category: "U.S. Federal", emoji: "🏛️" },
  { name: "adl-aicc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "adlnet", category: "U.S. Federal", emoji: "🏛️" },
  { name: "afrl", category: "U.S. Federal", emoji: "🏛️" },
  { name: "arcticlcc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "BBGInnovate", category: "U.S. Federal", emoji: "🏛️" },
  { name: "bfelob", category: "U.S. Federal", emoji: "🏛️" },
  { name: "blue-button", category: "U.S. Federal", emoji: "🏛️" },
  { name: "businessusa", category: "U.S. Federal", emoji: "🏛️" },
  { name: "CA-CST-Library", category: "U.S. Federal", emoji: "🏛️" },
  { name: "CA-CST-SII", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ccmc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "CDCgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "cfpb", category: "U.S. Federal", emoji: "🏛️" },
  { name: "cigiegov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "cisagov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "cloud-gov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "cmsgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "Code-dot-mil", category: "U.S. Federal", emoji: "🏛️" },
  { name: "commercedataservice", category: "U.S. Federal", emoji: "🏛️" },
  { name: "commercegov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "demand-driven-open-data", category: "U.S. Federal", emoji: "🏛️" },
  { name: "department-of-veterans-affairs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "dhs-gov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "didsr", category: "U.S. Federal", emoji: "🏛️" },
  { name: "digital-analytics-program", category: "U.S. Federal", emoji: "🏛️" },
  { name: "dodcio", category: "U.S. Federal", emoji: "🏛️" },
  { name: "doecode", category: "U.S. Federal", emoji: "🏛️" },
  { name: "doi-open-data", category: "U.S. Federal", emoji: "🏛️" },
  { name: "EEOC", category: "U.S. Federal", emoji: "🏛️" },
  { name: "energyapps", category: "U.S. Federal", emoji: "🏛️" },
  { name: "erdc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "eregs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "FAA-Aviation-Data-Portal", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fcc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fda", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fecgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "Federal-Aviation-Administration", category: "U.S. Federal", emoji: "🏛️" },
  { name: "federal-courts-software-factory", category: "U.S. Federal", emoji: "🏛️" },
  { name: "federaltradecommission", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fedramp", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fedspendingtransparency", category: "U.S. Federal", emoji: "🏛️" },
  { name: "fema", category: "U.S. Federal", emoji: "🏛️" },
  { name: "firelab", category: "U.S. Federal", emoji: "🏛️" },
  { name: "globegit", category: "U.S. Federal", emoji: "🏛️" },
  { name: "gopleader", category: "U.S. Federal", emoji: "🏛️" },
  { name: "government-services", category: "U.S. Federal", emoji: "🏛️" },
  { name: "GrainGenes", category: "U.S. Federal", emoji: "🏛️" },
  { name: "gsa", category: "U.S. Federal", emoji: "🏛️" },
  { name: "gsa-oes", category: "U.S. Federal", emoji: "🏛️" },
  { name: "gsa-tts", category: "U.S. Federal", emoji: "🏛️" },
  { name: "hhs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "HHS-AHRQ", category: "U.S. Federal", emoji: "🏛️" },
  { name: "HHSDigitalMediaAPIPlatform", category: "U.S. Federal", emoji: "🏛️" },
  { name: "HHSIDEAlab", category: "U.S. Federal", emoji: "🏛️" },
  { name: "historyatstate", category: "U.S. Federal", emoji: "🏛️" },
  { name: "IIP-Design", category: "U.S. Federal", emoji: "🏛️" },
  { name: "IMDProjects", category: "U.S. Federal", emoji: "🏛️" },
  { name: "imls", category: "U.S. Federal", emoji: "🏛️" },
  { name: "informaticslab", category: "U.S. Federal", emoji: "🏛️" },
  { name: "Innovation-Toolkit", category: "U.S. Federal", emoji: "🏛️" },
  { name: "internationaltradeadministration", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ioos", category: "U.S. Federal", emoji: "🏛️" },
  { name: "IRSgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "keplergo", category: "U.S. Federal", emoji: "🏛️" },
  { name: "libraryofcongress", category: "U.S. Federal", emoji: "🏛️" },
  { name: "M-O-S-E-S", category: "U.S. Federal", emoji: "🏛️" },
  { name: "mcc-gov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "missioncommand", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nasa", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nasa-develop", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nasa-gibs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NASA-rdt", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nasa-tournament-lab", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nasaworldwind", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NationalGuard", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nationalparkservice", category: "U.S. Federal", emoji: "🏛️" },
  { name: "navadmc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NCI-Agency", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NCRN", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NeoGeographyToolkit", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nesii", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ngds", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nhanes", category: "U.S. Federal", emoji: "🏛️" },
  { name: "nidcd", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NIEM", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NMB-Dev", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NMML", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NOAA-EPIC", category: "U.S. Federal", emoji: "🏛️" },
  { name: "noaa-gfdl", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NOAA-ORR-ERD", category: "U.S. Federal", emoji: "🏛️" },
  { name: "noaa-pmel", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ntia", category: "U.S. Federal", emoji: "🏛️" },
  { name: "NUWCDIVNPT", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ombegov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "Open-Sat", category: "U.S. Federal", emoji: "🏛️" },
  { name: "opengovplatform", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ozoneplatform", category: "U.S. Federal", emoji: "🏛️" },
  { name: "peacecorps", category: "U.S. Federal", emoji: "🏛️" },
  { name: "petsc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "presidential-innovation-fellows", category: "U.S. Federal", emoji: "🏛️" },
  { name: "project-open-data", category: "U.S. Federal", emoji: "🏛️" },
  { name: "radiofreeasia", category: "U.S. Federal", emoji: "🏛️" },
  { name: "redhawksdr", category: "U.S. Federal", emoji: "🏛️" },
  { name: "regulationsgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "sbstusa", category: "U.S. Federal", emoji: "🏛️" },
  { name: "SelectUSA", category: "U.S. Federal", emoji: "🏛️" },
  { name: "SERVIR", category: "U.S. Federal", emoji: "🏛️" },
  { name: "SSAgov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "state-hiu", category: "U.S. Federal", emoji: "🏛️" },
  { name: "sunpy", category: "U.S. Federal", emoji: "🏛️" },
  { name: "us-bea", category: "U.S. Federal", emoji: "🏛️" },
  { name: "US-CBP", category: "U.S. Federal", emoji: "🏛️" },
  { name: "US-Department-of-the-Treasury", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usagov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usaid", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usasearch", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usbr", category: "U.S. Federal", emoji: "🏛️" },
  { name: "uscensusbureau", category: "U.S. Federal", emoji: "🏛️" },
  { name: "uscis", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-ars-agil", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-ars-gbru", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-ars-ltar", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-ars-nwrc", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-ars-wmsru", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USDA-ERS", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USDA-FSA", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-nifa-b-team", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usda-vs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usdaForestService", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usdepartmentoflabor", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usdoj", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usdot-fhwa-stol", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usdot-jpo-ode", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usds", category: "U.S. Federal", emoji: "🏛️" },
  { name: "useda", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usepa", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USFWS", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usg-scope", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USGCRP", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usgpo", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usgs", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USGS-Astrogeology", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usgs-cmg", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usgs-eros", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USGS-OWI", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USGS-R", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USGS-WiM", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usnationalarchives", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usopm", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USPS", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USPTO", category: "U.S. Federal", emoji: "🏛️" },
  { name: "USSBA", category: "U.S. Federal", emoji: "🏛️" },
  { name: "usstatedept", category: "U.S. Federal", emoji: "🏛️" },
  { name: "ustaxcourt", category: "U.S. Federal", emoji: "🏛️" },
  { name: "uswds", category: "U.S. Federal", emoji: "🏛️" },
  { name: "VHAINNOVATIONS", category: "U.S. Federal", emoji: "🏛️" },
  { name: "virtual-world-framework", category: "U.S. Federal", emoji: "🏛️" },
  { name: "visionworkbench", category: "U.S. Federal", emoji: "🏛️" },
  { name: "weather-gov", category: "U.S. Federal", emoji: "🏛️" },
  { name: "WFMRDA", category: "U.S. Federal", emoji: "🏛️" },
  { name: "whitehouse", category: "U.S. Federal", emoji: "🏛️" },
  { name: "XDgov", category: "U.S. Federal", emoji: "🏛️" },

  // ── U.S. Military & Intelligence (17 orgs) ───────────────────────────────
  { name: "afseo", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "CRREL", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "deptofdefense", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "dod-cyber-crime-center", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "erdc-itl", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "iadgov", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "info-sharing-environment", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "NationalSecurityAgency", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "ngageoint", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "nsacyber", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "project-interoperability", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "psns-imf", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "shareandprotect", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "SIMP", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "transcom", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "usarmyresearchlab", category: "U.S. Military & Intelligence", emoji: "🪖" },
  { name: "USNavalResearchLaboratory", category: "U.S. Military & Intelligence", emoji: "🪖" },

  // ── U.S. States (52 orgs) ────────────────────────────────────────────────
  { name: "agrc", category: "U.S. States", emoji: "🗺️" },
  { name: "akhealth", category: "U.S. States", emoji: "🗺️" },
  { name: "azgs", category: "U.S. States", emoji: "🗺️" },
  { name: "cagov", category: "U.S. States", emoji: "🗺️" },
  { name: "CAWaterBoardDataCenter", category: "U.S. States", emoji: "🗺️" },
  { name: "ccap", category: "U.S. States", emoji: "🗺️" },
  { name: "CentralValleyModeling", category: "U.S. States", emoji: "🗺️" },
  { name: "coloradodemography", category: "U.S. States", emoji: "🗺️" },
  { name: "CTOpenData", category: "U.S. States", emoji: "🗺️" },
  { name: "DCGovWeb", category: "U.S. States", emoji: "🗺️" },
  { name: "eHawaii", category: "U.S. States", emoji: "🗺️" },
  { name: "FGS-FloridaGeologicalSurvey", category: "U.S. States", emoji: "🗺️" },
  { name: "gaepdit", category: "U.S. States", emoji: "🗺️" },
  { name: "gocodecolorado", category: "U.S. States", emoji: "🗺️" },
  { name: "IDAHO-DOC-NCOMS", category: "U.S. States", emoji: "🗺️" },
  { name: "idahofishgame", category: "U.S. States", emoji: "🗺️" },
  { name: "judicialcouncilcalifornia", category: "U.S. States", emoji: "🗺️" },
  { name: "la-ots", category: "U.S. States", emoji: "🗺️" },
  { name: "LADCO", category: "U.S. States", emoji: "🗺️" },
  { name: "LibraryofVA", category: "U.S. States", emoji: "🗺️" },
  { name: "massgov", category: "U.S. States", emoji: "🗺️" },
  { name: "MESMD", category: "U.S. States", emoji: "🗺️" },
  { name: "MFWP-GIS", category: "U.S. States", emoji: "🗺️" },
  { name: "nebraskamap", category: "U.S. States", emoji: "🗺️" },
  { name: "nelegislature", category: "U.S. States", emoji: "🗺️" },
  { name: "NJOGIS", category: "U.S. States", emoji: "🗺️" },
  { name: "njstatelibrary", category: "U.S. States", emoji: "🗺️" },
  { name: "ny", category: "U.S. States", emoji: "🗺️" },
  { name: "nys-its", category: "U.S. States", emoji: "🗺️" },
  { name: "nysenate", category: "U.S. States", emoji: "🗺️" },
  { name: "oimt", category: "U.S. States", emoji: "🗺️" },
  { name: "okcareertech", category: "U.S. States", emoji: "🗺️" },
  { name: "oregonopendata", category: "U.S. States", emoji: "🗺️" },
  { name: "ORMetro", category: "U.S. States", emoji: "🗺️" },
  { name: "scgeology", category: "U.S. States", emoji: "🗺️" },
  { name: "SLNC-DIMP", category: "U.S. States", emoji: "🗺️" },
  { name: "State-of-Arizona", category: "U.S. States", emoji: "🗺️" },
  { name: "StateOfCalifornia", category: "U.S. States", emoji: "🗺️" },
  { name: "swibwi", category: "U.S. States", emoji: "🗺️" },
  { name: "tndidd", category: "U.S. States", emoji: "🗺️" },
  { name: "TNRIS", category: "U.S. States", emoji: "🗺️" },
  { name: "twdb", category: "U.S. States", emoji: "🗺️" },
  { name: "TxDOT", category: "U.S. States", emoji: "🗺️" },
  { name: "UtahForestryFireStateLands", category: "U.S. States", emoji: "🗺️" },
  { name: "VDGIF", category: "U.S. States", emoji: "🗺️" },
  { name: "Virginia-Department-of-Health", category: "U.S. States", emoji: "🗺️" },
  { name: "Virginia-House-of-Delegates", category: "U.S. States", emoji: "🗺️" },
  { name: "vtrans", category: "U.S. States", emoji: "🗺️" },
  { name: "vtrans-rail", category: "U.S. States", emoji: "🗺️" },
  { name: "WA-Department-of-Agriculture", category: "U.S. States", emoji: "🗺️" },
  { name: "wsdot", category: "U.S. States", emoji: "🗺️" },
  { name: "WSDOT-GIS", category: "U.S. States", emoji: "🗺️" },

  // ── U.S. Cities (66 orgs) ────────────────────────────────────────────────
  { name: "austincodeit", category: "U.S. Cities", emoji: "🏙️" },
  { name: "Baltimore-City-EGIS", category: "U.S. Cities", emoji: "🏙️" },
  { name: "berkeleypubliclibrary", category: "U.S. Cities", emoji: "🏙️" },
  { name: "BostonRedevelop", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cambridgedata", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cambridgegis", category: "U.S. Cities", emoji: "🏙️" },
  { name: "chicago", category: "U.S. Cities", emoji: "🏙️" },
  { name: "city-of-bellingham", category: "U.S. Cities", emoji: "🏙️" },
  { name: "city-of-bloomington", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofasheville", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfAuburnAL", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofaustin", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofboise", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfBoston", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofboulder", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofburlington", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofchattanooga", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfDetroit", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfLosAngeles", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofnewyork", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfPhiladelphia", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityofPittsburgh", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofportland", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityofReno", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityofSanFrancisco", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityofSantaMonica", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofsomerville", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofvernonia", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityOfVirginiaBeach", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cityofwestsacramento", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CityofYakima", category: "U.S. Cities", emoji: "🏙️" },
  { name: "cno-opa", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CORaleigh", category: "U.S. Cities", emoji: "🏙️" },
  { name: "CUMTD", category: "U.S. Cities", emoji: "🏙️" },
  { name: "DCCouncil", category: "U.S. Cities", emoji: "🏙️" },
  { name: "DCgov", category: "U.S. Cities", emoji: "🏙️" },
  { name: "DenverDev", category: "U.S. Cities", emoji: "🏙️" },
  { name: "digitalinclusion", category: "U.S. Cities", emoji: "🏙️" },
  { name: "egovpdx", category: "U.S. Cities", emoji: "🏙️" },
  { name: "Honolulu", category: "U.S. Cities", emoji: "🏙️" },
  { name: "kcmo", category: "U.S. Cities", emoji: "🏙️" },
  { name: "lfucg", category: "U.S. Cities", emoji: "🏙️" },
  { name: "longbeachinnovationteam", category: "U.S. Cities", emoji: "🏙️" },
  { name: "LouisvilleMetro", category: "U.S. Cities", emoji: "🏙️" },
  { name: "louisvillemetro-innovation", category: "U.S. Cities", emoji: "🏙️" },
  { name: "mnhrc", category: "U.S. Cities", emoji: "🏙️" },
  { name: "mnylc", category: "U.S. Cities", emoji: "🏙️" },
  { name: "moda-nyc", category: "U.S. Cities", emoji: "🏙️" },
  { name: "monum", category: "U.S. Cities", emoji: "🏙️" },
  { name: "NewYorkCityCouncil", category: "U.S. Cities", emoji: "🏙️" },
  { name: "NYCComptroller", category: "U.S. Cities", emoji: "🏙️" },
  { name: "nycdot", category: "U.S. Cities", emoji: "🏙️" },
  { name: "NYCPlanning", category: "U.S. Cities", emoji: "🏙️" },
  { name: "onc-healthit", category: "U.S. Cities", emoji: "🏙️" },
  { name: "OpenGovDC", category: "U.S. Cities", emoji: "🏙️" },
  { name: "p2g", category: "U.S. Cities", emoji: "🏙️" },
  { name: "pdxgis", category: "U.S. Cities", emoji: "🏙️" },
  { name: "PierceCountyWA", category: "U.S. Cities", emoji: "🏙️" },
  { name: "ProBonoDC", category: "U.S. Cities", emoji: "🏙️" },
  { name: "ridertd", category: "U.S. Cities", emoji: "🏙️" },
  { name: "SantaClarita", category: "U.S. Cities", emoji: "🏙️" },
  { name: "sfbart", category: "U.S. Cities", emoji: "🏙️" },
  { name: "SiloamSprings", category: "U.S. Cities", emoji: "🏙️" },
  { name: "southbendin", category: "U.S. Cities", emoji: "🏙️" },
  { name: "TownOfBrookline", category: "U.S. Cities", emoji: "🏙️" },
  { name: "tucsonaz", category: "U.S. Cities", emoji: "🏙️" },

  // ── U.S. Counties (18 orgs) ──────────────────────────────────────────────
  { name: "anoka-script-team", category: "U.S. Counties", emoji: "🏘️" },
  { name: "ArlingtonCounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "baltimorecounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "BayAreaMetro", category: "U.S. Counties", emoji: "🏘️" },
  { name: "bouldercounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "Canyon-County", category: "U.S. Counties", emoji: "🏘️" },
  { name: "CarverCounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "donaanacounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "fairfieldcountyit", category: "U.S. Counties", emoji: "🏘️" },
  { name: "fpdcc", category: "U.S. Counties", emoji: "🏘️" },
  { name: "HarrisCountyFOA", category: "U.S. Counties", emoji: "🏘️" },
  { name: "HennepinCountyPublicDefender", category: "U.S. Counties", emoji: "🏘️" },
  { name: "LACMTA", category: "U.S. Counties", emoji: "🏘️" },
  { name: "MCLD", category: "U.S. Counties", emoji: "🏘️" },
  { name: "pottcountyit", category: "U.S. Counties", emoji: "🏘️" },
  { name: "saccounty", category: "U.S. Counties", emoji: "🏘️" },
  { name: "sfcta", category: "U.S. Counties", emoji: "🏘️" },
  { name: "slugis", category: "U.S. Counties", emoji: "🏘️" },

  // ── U.S. Special Districts (10 orgs) ─────────────────────────────────────
  // Regional planning authorities, transit agencies, port authorities, etc.
  { name: "atlregional", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "AZMAG", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "baaqmd", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "cleveland-metroparks", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "CMAP-REPOS", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "commonwealth-of-puerto-rico", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "MAPC", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "Metropolitan-Council", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "portofsandiego", category: "U.S. Special Districts", emoji: "🔷" },
  { name: "psrc", category: "U.S. Special Districts", emoji: "🔷" },

  // ── U.S. Tribal Nations (3 orgs) ─────────────────────────────────────────
  { name: "coquille-indian-tribe", category: "U.S. Tribal Nations", emoji: "🪶" },
  { name: "MSBandofChoctawIndians", category: "U.S. Tribal Nations", emoji: "🪶" },
  { name: "osage-nation", category: "U.S. Tribal Nations", emoji: "🪶" },

  // ── U.S. Law Enforcement (1 org) ─────────────────────────────────────────
  { name: "SanDiegoCountySheriff", category: "U.S. Law Enforcement", emoji: "🚔" },
];

/**
 * All category values that appear in ORGS, plus "All" for the unfiltered view.
 * Used to populate the category filter dropdown.
 */
export const CATEGORIES = [
  "All",
  "U.S. Federal",
  "U.S. Military & Intelligence",
  "U.S. States",
  "U.S. Cities",
  "U.S. Counties",
  "U.S. Special Districts",
  "U.S. Tribal Nations",
  "U.S. Law Enforcement",
];
